-- MySQL Script generated by MySQL Workbench
-- Wed Apr  5 00:41:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema demotiktok
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema demotiktok
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demotiktok` DEFAULT CHARACTER SET utf8mb4 ;
USE `demotiktok` ;

-- -----------------------------------------------------
-- Table `demotiktok`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demotiktok`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL DEFAULT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `version` BIGINT(20) NULL DEFAULT NULL,
  `is_persistente` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `demotiktok`.`bike`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demotiktok`.`bike` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(150) NULL DEFAULT NULL,
  `model` VARCHAR(150) NULL DEFAULT NULL,
  `version` BIGINT(20) NULL DEFAULT NULL,
  `is_persistente` TINYINT(1) NULL DEFAULT NULL,
  `id_user` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_bike_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_bike`
    FOREIGN KEY (`id_user`)
    REFERENCES `demotiktok`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `demotiktok`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demotiktok`.`car` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(150) NULL DEFAULT NULL,
  `model` VARCHAR(150) NULL DEFAULT NULL,
  `version` BIGINT(20) NULL DEFAULT NULL,
  `is_persistente` TINYINT(1) NULL DEFAULT NULL,
  `id_user` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_car_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_car`
    FOREIGN KEY (`id_user`)
    REFERENCES `demotiktok`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
